<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL2udDJW\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL2udDJW/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerL2udDJW.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerL2udDJW\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerL2udDJW\appAppKernelProdContainer([
    'container.build_hash' => 'L2udDJW',
    'container.build_id' => '7be61d70',
    'container.build_time' => 1704257520,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL2udDJW');
